import { Post } from './post.model';

export const POSTS: Post[] = [
  new Post("Already wealthy man wins lottery", "people", `Lorem ipsum dolor sit amet, aliquam massa luctus, urna nisl sodales, dictum volutpat commodo semper. Eros auctor accumsan magna egestas hac, pulvinar viverra hymenaeos quaerat, dui ut scelerisque. Leo adipiscing hac vel cras curabitur, at metus, vitae nec nisl eu sed. Dui gravida consectetuer ipsum vel luctus, euismod ligula cras. Cursus duis, ornare pede enim sem urna nibh, urna fermentum integer vel magna, nam sed vivamus est praesent. Nibh sit nunc, class in libero enim erat. Tincidunt dis turpis. Consectetuer accumsan nunc libero purus ut.
`, new Date(), 'http://cdn.moneycrashers.com/wp-content/uploads/2011/06/falling-dollars-lotto-winner.jpg', 0),
  new Post("Housing prices in Portland rise again; experts blame Californians", "places", `Lorem ipsum dolor sit amet, aliquam massa luctus, urna nisl sodales, dictum volutpat commodo semper. Eros auctor accumsan magna egestas hac, pulvinar viverra hymenaeos quaerat, dui ut scelerisque. Leo adipiscing hac vel cras curabitur, at metus, vitae nec nisl eu sed. Dui gravida consectetuer ipsum vel luctus, euismod ligula cras. Cursus duis, ornare pede enim sem urna nibh, urna fermentum integer vel magna, nam sed vivamus est praesent. Nibh sit nunc, class in libero enim erat. Tincidunt dis turpis. Consectetuer accumsan nunc libero purus ut.
`, new Date(), "http://i.imgur.com/kpnaVlZ.jpg", 1),
  new Post("Prominent Politician refutes fact-based science", "people", `Lorem ipsum dolor sit amet, aliquam massa luctus, urna nisl sodales, dictum volutpat commodo semper. Eros auctor accumsan magna egestas hac, pulvinar viverra hymenaeos quaerat, dui ut scelerisque. Leo adipiscing hac vel cras curabitur, at metus, vitae nec nisl eu sed. Dui gravida consectetuer ipsum vel luctus, euismod ligula cras. Cursus duis, ornare pede enim sem urna nibh, urna fermentum integer vel magna, nam sed vivamus est praesent. Nibh sit nunc, class in libero enim erat. Tincidunt dis turpis. Consectetuer accumsan nunc libero purus ut.
`, new Date(), "https://regmedia.co.uk/2015/09/15/dunce_cap_648.jpg?x=648&y=348&crop=1", 2),
  new Post("Justin Beiber releases mixtape of Beatles classics", "music", `Lorem ipsum dolor sit amet, aliquam massa luctus, urna nisl sodales, dictum volutpat commodo semper. Eros auctor accumsan magna egestas hac, pulvinar viverra hymenaeos quaerat, dui ut scelerisque. Leo adipiscing hac vel cras curabitur, at metus, vitae nec nisl eu sed. Dui gravida consectetuer ipsum vel luctus, euismod ligula cras. Cursus duis, ornare pede enim sem urna nibh, urna fermentum integer vel magna, nam sed vivamus est praesent. Nibh sit nunc, class in libero enim erat. Tincidunt dis turpis. Consectetuer accumsan nunc libero purus ut.
`, new Date(), "http://jamaicatakeout.com/wp-content/uploads/2015/04/justin-bieber.png", 3),
  new Post("Real garbagemen of Clevelend renewed for another season", "tv", `Lorem ipsum dolor sit amet, aliquam massa luctus, urna nisl sodales, dictum volutpat commodo semper. Eros auctor accumsan magna egestas hac, pulvinar viverra hymenaeos quaerat, dui ut scelerisque. Leo adipiscing hac vel cras curabitur, at metus, vitae nec nisl eu sed. Dui gravida consectetuer ipsum vel luctus, euismod ligula cras. Cursus duis, ornare pede enim sem urna nibh, urna fermentum integer vel magna, nam sed vivamus est praesent. Nibh sit nunc, class in libero enim erat. Tincidunt dis turpis. Consectetuer accumsan nunc libero purus ut.
`, new Date(), "https://afv.com/wp-content/uploads/2014/10/garbage.jpg", 4),
  new Post("Critics proclaim new album by very famous band to be better than their older stuff", "music", `Lorem ipsum dolor sit amet, aliquam massa luctus, urna nisl sodales, dictum volutpat commodo semper. Eros auctor accumsan magna egestas hac, pulvinar viverra hymenaeos quaerat, dui ut scelerisque. Leo adipiscing hac vel cras curabitur, at metus, vitae nec nisl eu sed. Dui gravida consectetuer ipsum vel luctus, euismod ligula cras. Cursus duis, ornare pede enim sem urna nibh, urna fermentum integer vel magna, nam sed vivamus est praesent. Nibh sit nunc, class in libero enim erat. Tincidunt dis turpis. Consectetuer accumsan nunc libero purus ut.
`, new Date(), "https://thevelvetcafe.files.wordpress.com/2011/11/critic.jpg", 5)
];
